### ISSUE TITLE
What configure options are we using and why ? 

### ISSUE THREAD

**Issue by brucellino** [SouthAfricaDigitalScience/torque-2.5#2]
TORQUE can be compiled with several options. Can you please explain 

  1. What the options are available to TORQUE (ie. what does `./configure --help` say ?)
  1. What options were chosen for this site ? (which I assume for now to be the "generic" site.

**Comment by smasoka** [comment]
1. Plenty of options are available
2. Since its generic, there are no special options just `without-tcl` 

Mainly i need this installation for the libraries for openmpi. Otherwise special options like enable gpus and drmaa can be coded.

**Comment by brucellino** [comment]
Ok. See #3 for the discussion around suggestions for branch conventions.
