### ISSUE TITLE
check the url - 403

### ISSUE THREAD

**Issue by brucellino** [SouthAfricaDigitalScience/torque-2.5#4]
I'm getting Access denied on http://wpfilebase.s3.amazonaws.com/ - the url used in the build script. Can you confirm that it's the correct one ?

**Comment by smasoka** [comment]
yes the full link http://wpfilebase.s3.amazonaws.com/torque/torque-2.5.13.tar.gz -  works

**Comment by brucellino** [comment]
looks like direct requests don't work - 
in job 1 : 

```
Connecting to wpfilebase.s3.amazonaws.com|54.231.168.98|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-08-13 17:04:15 ERROR 403: Forbidden.

Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by brucellino** [comment]
on 72f1d379214d79a6155a7886664f289103bef240 we're getting 
```
continuing from previous builds, using source at  /repo/src/torque/2.5.13/torque-2.5.13.tar.gz
untar the tarball

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

how did the tarball get there in the first place ?

**Comment by brucellino** [comment]
Seems like it was pulled in by a build, after having been cleaned out - so the url in the build script is legit.
